version: "3.8"

services:
  backend:
    build:
      context: ./backend-ai
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend-ai:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
    command: npm run dev
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
